### ISSUE TITLE
Namespace issues with objects in multiple source files

### ISSUE THREAD

**Issue by theoretical2019** [lidatong/dataclasses-json#208]
I have a simple hierarchy with three files.  First `nodes.py` defines a couple node types and `Element` as a `Union` of these:

```
# nodes.py
from dataclasses_json import dataclass_json

from dataclasses import dataclass, field
from typing import List, Tuple, Union, Dict

Element = Union["Alpha", "Beta"]

@dataclass_json
@dataclass
class Alpha:
    a: int

@dataclass_json
@dataclass
class Beta:
    b: int
```

Then I define a top level class that refers to the elements in a separate file:

```
# toplevel.py

from dataclasses_json import dataclass_json

from dataclasses import dataclass, field
from typing import List, Tuple, Union, Dict

import nodes

@dataclass_json
@dataclass
class Toplevel:
    elements: List[nodes.Element]
```

Then a main program to pull it all together:

```
#!/usr/bin/env python3                                                                                                                                                                                             
# demo.py

from dataclasses_json import dataclass_json

from dataclasses import dataclass, field
from typing import List, Tuple, Union, Dict

import toplevel

#import nodes                                                                                                                                                                                                      
#value = toplevel.Toplevel([nodes.Alpha(a=3), nodes.Beta(b=5)])                                                                                                                                                    
#encoded = value.to_json()                                                                                                                                                                                         

encoded = '{"elements": [{"a": 3}, {"b": 5}]}'
print(encoded)
decoded = toplevel.Toplevel.from_json(encoded)
print(decoded)
```

Running `demo.py` gives the following traceback:

```
Traceback (most recent call last):
  File "./demo.py", line 16, in <module>
    decoded = toplevel.Toplevel.from_json(encoded)
  File "~/ve/lib/python3.6/site-packages/dataclasses_json/api.py", line 78, in from_json
    return cls.from_dict(kvs, infer_missing=infer_missing)
  File "~/ve/lib/python3.6/site-packages/dataclasses_json/api.py", line 85, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "~/ve/lib/python3.6/site-packages/dataclasses_json/core.py", line 143, in _decode_dataclass
    types = get_type_hints(cls)
  File "/usr/lib/python3.6/typing.py", line 1515, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "/usr/lib/python3.6/typing.py", line 350, in _eval_type
    return t._eval_type(globalns, localns)
  File "/usr/lib/python3.6/typing.py", line 1055, in _eval_type
    in self.__args__) if self.__args__ else None
  File "/usr/lib/python3.6/typing.py", line 1054, in <genexpr>
    ev_args = tuple(_eval_type(a, globalns, localns) for a
  File "/usr/lib/python3.6/typing.py", line 350, in _eval_type
    return t._eval_type(globalns, localns)
  File "/usr/lib/python3.6/typing.py", line 762, in _eval_type
    ev_args = tuple(_eval_type(t, globalns, localns) for t in self.__args__)
  File "/usr/lib/python3.6/typing.py", line 762, in <genexpr>
    ev_args = tuple(_eval_type(t, globalns, localns) for t in self.__args__)
  File "/usr/lib/python3.6/typing.py", line 350, in _eval_type
    return t._eval_type(globalns, localns)
  File "/usr/lib/python3.6/typing.py", line 245, in _eval_type
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Alpha' is not defined
```

The problem is only in the `from` direction.  The commented-out lines work; they successfully initialize `encoded` by calling `to_json()` on an object (instead of using a hard-coded JSON string).  In this case `from_json()` also fails with the same traceback (which seems reasonable, since the string is exactly the same).

As a workaround, I've discovered that adding `from nodes import Element, Alpha, Beta` to `toplevel.py` makes the error go away.

Perhaps the issue is `get_type_hints()` takes parameters for namespaces, but `dataclasses-json` isn't passing any?

Possibly relevant system info:

```
$ cat /etc/issue
Ubuntu 18.04.4 LTS \n \l
$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
$ pip freeze
dataclasses==0.7
dataclasses-json==0.4.2
importlib-metadata==1.6.0
importlib-resources==1.4.0
Jinja2==2.11.1
MarkupSafe==1.1.1
marshmallow==3.5.1
marshmallow-enum==1.5.1
mypy-extensions==0.4.3
pkg-resources==0.0.0
pluginbase==1.0.0
stringcase==1.2.0
typing-extensions==3.7.4.2
typing-inspect==0.5.0
zipp==3.1.0
```

(I actually found this with a much more complex codebase, what I've posted here is a minimal example that reproduces the bug)

**Comment by lidatong** [comment]
hi, thanks for reporting this and detailing a simplified example

I believe this is a limitation of `typing` itself rather than this library. your definition of `Element` is evaluated by `get_type_hints`, which happens before the class decl of `Alpha`. 
reading the [documentation for `get_type_hints`](https://docs.python.org/3/library/typing.html#typing.get_type_hints) it's not clear to me whether this is or is not something that should be supported

i imagine forward references are primarily useful for recursive types though, and moving the definition of `Element` to the end of the file, and using the class names rather than strings seems to resolve the issue.

```python
...
class Beta:
    b: int

Element = Union[Alpha, Beta]
```

i recognize this might not be quite as clearcut in your actual codebase -- let me know your thoughts
