### ISSUE TITLE
Issue with the dataclasses-json Library in Python 3.8 and AWS Lambda

### ISSUE THREAD

**Issue by mvillafuertem** [lidatong/dataclasses-json#244]
Hi there, I'm having trouble trying to run this example with AWS Lambda. Any suggestions on how to fix it? Thanks!

```requirements.txt
dataclasses==0.6
dataclasses-json==0.5.2
```

```python

# same imports as above, with the additional `LetterCase` import
from dataclasses import dataclass
from dataclasses_json import dataclass_json, LetterCase
import logging

# LOGGER
logging.basicConfig()
logger = logging.getLogger()
logger.setLevel('INFO')

@dataclass_json(letter_case=LetterCase.CAMEL)  # now all fields are encoded/decoded from camelCase
@dataclass
class ConfiguredSimpleExample:
    int_field: int



def lambda_handler(event, context):
    logger.info("payload: %s", event)
    ConfiguredSimpleExample(1).to_json()  # {"intField": 1}
    ConfiguredSimpleExample.from_json('{"intField": 1}')  # ConfiguredSimpleExample(1)


if __name__ == "__main__":
    lambda_handler({}, [])


```

```
[ERROR] AttributeError: module 'typing' has no attribute '_ClassVar'
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/main.py", line 40, in <module>
    class Message:
  File "/var/task/dataclasses.py", line 958, in dataclass
    return wrap(_cls)
  File "/var/task/dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/var/task/dataclasses.py", line 800, in _process_class
    cls_fields = [_get_field(cls, name, type)
  File "/var/task/dataclasses.py", line 800, in <listcomp>
    cls_fields = [_get_field(cls, name, type)
  File "/var/task/dataclasses.py", line 659, in _get_field
    if (_is_classvar(a_type, typing)
  File "/var/task/dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar
```

**Comment by mvillafuertem** [comment]
When I run this example without dataclasses-json library, everything works fine.

```python
import logging
from dataclasses import dataclass

# LOGGER
logging.basicConfig()
logger = logging.getLogger()
logger.setLevel('INFO')


@dataclass
class ConfiguredSimpleExample:
    int_field: int


def lambda_handler(event, context):
    logger.info("payload: %s", ConfiguredSimpleExample(1))


# docker run -p 6379:6379 -e ALLOW_EMPTY_PASSWORD=yes  bitnami/redis:latest
if __name__ == "__main__":
    lambda_handler({}, [])


```

**Comment by mvillafuertem** [comment]
Workaround 

```python

import logging
from dataclasses import dataclass, asdict

# LOGGER
logging.basicConfig()
logger = logging.getLogger()
logger.setLevel('INFO')


@dataclass
class ConfiguredSimpleExample:
    int_field: int


def lambda_handler(event, context):
    configured_simple_example = ConfiguredSimpleExample(1)
    configured_simple_example_to_json = json.dumps(asdict(configured_simple_example))
    configured_simple_example_from_json = ConfiguredSimpleExample(**json.loads(configured_simple_example_to_json))
    logger.info("payload: %s", configured_simple_example_to_json)
    logger.info("payload: %s", configured_simple_example_from_json)


if __name__ == "__main__":
    lambda_handler({}, [])

```

**Comment by george-zubrienko** [comment]
Not really a workaround since it doesn't use the lib - feel free to reopen if still a problem
