### ISSUE TITLE
Can't convert dict of dataclass back to dataclass

### ISSUE THREAD

**Issue by tautomer** [lidatong/dataclasses-json#277]
Here is a MWE.

I took ["A larger example" in the official doc](https://lidatong.github.io/dataclasses-json/#quickstart), and changed the the list of dataclass to a dict of dataclass

```python
from dataclasses import dataclass
from dataclasses_json import dataclass_json

@dataclass_json
@dataclass(frozen=True)
class Minion:
    name: str


@dataclass_json
@dataclass(frozen=True)
class Boss:
    minions: dict[Minion]

boss = Boss({'evil minion': Minion('evil minion'), 'very evil minion': Minion('very evil minion')})
boss_json = """
{
    "minions": {
        "evil minion": {
            "name": "evil minion"
        },
        "very evil minion": {
            "name": "very evil minion"
        }
    }
}
""".strip()
assert boss.to_json(indent=4) == boss_json
assert Boss.from_json(boss_json) == boss
```

The first aseertion is ok, but the second fails because `from_json` can't convert the string back to dataclass, with an error message of

```text
Traceback (most recent call last):
  File "test.py", line 61, in <module>
    assert Boss.from_json(boss_json) == boss
  File "AppData\Local\Programs\Python\Python39\lib\site-packages\dataclasses_json\api.py", line 76, in from_json
    return cls.from_dict(kvs, infer_missing=infer_missing)
  File "AppData\Local\Programs\Python\Python39\lib\site-packages\dataclasses_json\api.py", line 83, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "AppData\Local\Programs\Python\Python39\lib\site-packages\dataclasses_json\core.py", line 201, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
  File "AppData\Local\Programs\Python\Python39\lib\site-packages\dataclasses_json\core.py", line 251, in _decode_generic
    k_type, v_type = getattr(type_, "__args__", (Any, Any))
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by tautomer** [comment]
Turns out that Python 3.9 allows you to define like `minions: dict[Minion]`, which causes the error.

If I do `minions: Dict[str, Minion]`, there will be no problem.
