### ISSUE TITLE
ImportError in Python3.9

### ISSUE THREAD

**Issue by jingedawang** [lidatong/dataclasses-json#329]
In Python 3.9 environment, simply `from dataclasses_json import dataclass_json` will cause an error:
```
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from dataclasses_json import dataclass_json
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jingewang\AppData\Local\Programs\Python\Python39\lib\site-packages\dataclasses_json\__init__.py", line 2, in <module>
    from dataclasses_json.api import (DataClassJsonMixin,
  File "C:\Users\jingewang\AppData\Local\Programs\Python\Python39\lib\site-packages\dataclasses_json\api.py", line 11, in <module>
    from dataclasses_json.core import (Json, _ExtendedEncoder, _asdict,
  File "C:\Users\jingewang\AppData\Local\Programs\Python\Python39\lib\site-packages\dataclasses_json\core.py", line 17, in <module>
    from typing_inspect import is_union_type  # type: ignore
  File "C:\Users\jingewang\AppData\Local\Programs\Python\Python39\lib\site-packages\typing_inspect.py", line 17, in <module>
    from typing_extensions import _TypedDictMeta as _TypedDictMeta_TE
ImportError: cannot import name '_TypedDictMeta' from 'typing_extensions' (C:\Users\jingewang\AppData\Local\Programs\Python\Python39\lib\site-packages\typing_extensions.py)
```

Could you make sure if it is a bug?

**Comment by benridley** [comment]
This isn't an issue for me on 3.9, and I also tried installing the library fresh on a 3.9 container and it worked fine.

Seems like perhaps you have something funky going on with your Python installation. Have you tried using a virtual environment?

**Comment by jingedawang** [comment]
Thanks for your advice. I test it in the virtual environment and it works well.
