### ISSUE TITLE
When using `list[str]` as type hint, `TypeError: 'type' object is not subscriptable` occurred.

### ISSUE THREAD

**Issue by yuji38kwmt** [lidatong/dataclasses-json#331]
# Evironmental
* Python3.8.6
* dataclasses-json 0.4.5

# What's happend?

When I exected the following python file, `TypeError: 'type' object is not subscriptable` occurred.

```python
from __future__ import annotations
from dataclasses import dataclass
from dataclasses_json import dataclass_json


@dataclass_json
@dataclass
class Person:
    name: str
    club: list[str]


d = {"name": "Alice", "club": ["tennis", "soccer"]}
person = Person.from_dict(d)
print(person)
```

```
$ python foo.py
Traceback (most recent call last):
  File "foo2.py", line 14, in <module>
    person = Person.from_dict(d)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/dataclasses_json/api.py", line 83, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/dataclasses_json/core.py", line 152, in _decode_dataclass
    types = get_type_hints(cls)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/typing.py", line 1232, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/home/vagrant/.pyenv/versions/3.8.6/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: 'type' object is not subscriptable
```

When I change `list` to `typing.List`, the error did not occurred

# Supplementary
Related to https://qiita.com/yuji38kwmt/items/ce49efc91bb9b6430437

**Comment by julianfortune** [comment]
This is an issue with **Python 3.8**. From @Fatal1ty's [response to a similar `mashumaro` issue](https://github.com/Fatal1ty/mashumaro/issues/65#issuecomment-1004701854):

> The new syntax introduced in [PEP 585](https://www.python.org/dev/peps/pep-0585/) works on source level only for 3.9+. On older versions this syntax with `from __future__ import annotations` only works for annotations that is simply not enough for mashumaro.
> 
> See here for details: https://www.python.org/dev/peps/pep-0585/#backwards-compatibility
