### ISSUE TITLE
Recursive Data Structures

### ISSUE THREAD

**Issue by aersam** [lidatong/dataclasses-json#361]
I have a recursive data structure as follows:

```python
@dataclass_json
@dataclass
class TreeItems:
    data: TreeItemData
    Children: List["TreeItems"]
```

This does not work, even with the workaround here: https://github.com/lidatong/dataclasses-json/issues/340#issuecomment-1048277260 (infinite recursion)

Also I get a warning:

```
mm.py:271: UserWarning: Unknown type ForwardRef('TreeItems') at TreeItems.Children: typing.List[ForwardRef('TreeItems')] It's advised to pass the correct marshmallow type to `mm_field`
```

As a workaround I do a recursive function that corrects the nested types before serializing it to JSON:

```python
def _fix_resursion(dt: Union[List[Any], Dict[str, Any]]):
    if isinstance(dt, List):
        return [_fix_resursion(i) for i in dt]
    elif isinstance(dt, Dict):
        return {k: _fix_resursion(v) for k, v in dt.items()}
    elif hasattr(dt, "schema") and isinstance(dt, Callable):
        return _fix_resursion(type(dt).schema().dump(dt))
    else:
        return dt
```

Would be great to have Forward References  supported out-of-the box because it's the only thing I'm missing from this great library!

**Comment by johhnry** [comment]
Hi,

I have the same issue here:

```python
@dataclass_json
@dataclass
class Task:
    name: str
    children: List["Task"]
```

```
UserWarning: Unknown type ForwardRef('Task') at Task.children: typing.List[ForwardRef('Task')] It's advised to pass the correct marshmallow type to `mm_field`.
```

What I don't understand is that there's a special section in the README about recursive dataclasses: https://lidatong.github.io/dataclasses-json/#handle-recursive-dataclasses

This does not seem to work with

**Comment by matt035343** [comment]
Hi both,

I was not able to recreate any issues from above information, not even the warning (see below).

Can you confirm it is still an issue and provide information such as dataclasses-json version, python version, etc.?


```python
Task(name='no1', children=[Task(name='no2', children=[]), Task(name='no3', children=[Task(name='no4', children=[])])]).to_json()
```
```
'{"name": "no1", "children": [{"name": "no2", "children": []}, {"name": "no3", "children": [{"name": "no4", "children": []}]}]}'
```
```python
Task.from_json('{"name": "no1", "children": [{"name": "no2", "children": []}, {"name": "no3", "children": [{"name": "no4", "children": []}]}]}')
```
```
Task(name='no1', children=[Task(name='no2', children=[]), Task(name='no3', children=[Task(name='no4', children=[])])])
```

**Comment by johhnry** [comment]
Hi @matt035343,

Thanks for the follow up, I can confirm that it works on Python 3.11 / dataclasses-json 0.5.8:

```python
from dataclasses import dataclass
from dataclasses_json import dataclass_json

from typing import List


@dataclass_json
@dataclass
class Task:
    name: str
    children: List["Task"]


task = Task(name="A", children=[Task(name="B", children=[])])

print(task.to_json())
print(task.to_dict())

print(Task.from_json('{"name": "A", "children": [{"name": "B", "children": []}]}'))
```

```
{"name": "A", "children": [{"name": "B", "children": []}]}
{'name': 'A', 'children': [{'name': 'B', 'children': []}]}
Task(name='A', children=[Task(name='B', children=[])])
```

**Comment by matt035343** [comment]
@johhnry I am closing this issue, but please reopen if you encounter the issue again, e.g. in Python 3.7 and 3.8. Thank you.

**Comment by mgax** [comment]
I'm seeing the same warning with dataclasses-json 0.6.1, marshmallow 3.20.1, on Python 3.11.2:

```py
>>> from typing import List
>>> from dataclasses import dataclass
>>> from dataclasses_json import dataclass_json
>>> 
>>> @dataclass_json
... @dataclass
... class Task:
...     name: str
...     children: List["Task"]
... 
>>> 
>>> print(
...     Task.schema().loads(
...         """
...         {"name": "1", "children": []}
...         """
...     )
... )
/Users/mgax/.pyenv/versions/3.11.2/envs/dataclass-validation-prototype/lib/python3.11/site-packages/dataclasses_json/mm.py:288: UserWarning: Unknown type ForwardRef('Task') at Task.children: typing.List[ForwardRef('Task')] It's advised to pass the correct marshmallow type to `mm_field`.
  warnings.warn(
Task(name='1', children=[])
```

But what is really troubling me is that validation only seems to work for the top-level object, not for any nested objects. This fails as expected:

```py
>>> print(
...     Task.schema().loads(
...         """
...         {"name": "1", "children": [], "extra": "x"}
...         """
...     )
... )
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/mgax/.pyenv/versions/3.11.2/envs/dataclass-validation-prototype/lib/python3.11/site-packages/marshmallow/schema.py", line 756, in loads
    return self.load(data, many=many, partial=partial, unknown=unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mgax/.pyenv/versions/3.11.2/envs/dataclass-validation-prototype/lib/python3.11/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
           ^^^^^^^^^^^^^^
  File "/Users/mgax/.pyenv/versions/3.11.2/envs/dataclass-validation-prototype/lib/python3.11/site-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'extra': ['Unknown field.']}
```

This, however, ignores the extra field, with no validation error:

```py
>>> print(
...     Task.schema().loads(
...         """
...         {
...             "name": "1",
...             "children": [
...                 {"name": "2", "children": [], "extra": "x"}
...             ]
...         }
...         """
...     )
... )
Task(name='1', children=[Task(name='2', children=[])])
```
