### ISSUE TITLE
CatchAll not compatible with __futures__.annotations

### ISSUE THREAD

**Issue by stadelmanma** [lidatong/dataclasses-json#382]
# Problem
When using `from __future__ import annotations` along side a `CatchAll` field an error `dataclasses_json.undefined.UndefinedParameterError: No field of type dataclasses_json.CatchAll defined` is thrown. I added some print statements to [undefined](https://github.com/lidatong/dataclasses-json/blob/23e5eec42b173cf91a1ff194416ccbc87411df2e/dataclasses_json/undefined.py#L244) and was able to observe with the `__futures__` import the field type comes over as `'CatchAll'` instead of an instance of `typing.Optional[~CatchAllVar]`. 

## Minimal reproducible example:
```
from __future__ import annotations
from dataclasses import dataclass
from dataclasses_json import Undefined, CatchAll
from dataclasses_json import dataclass_json
from datetime import date


@dataclass_json(undefined=Undefined.INCLUDE)
@dataclass
class MyClassWithCatchAll:
    id: int = None
    type: int = None
    created_on: date = None
    details: dict[str, str] = None
    extras: CatchAll = None

MyClassWithCatchAll()

#####
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mstadelman/Development/iml/dataclasses-json/dataclasses_json/undefined.py", line 221, in _catch_all_init
    if _CatchAllUndefinedParameters._get_catch_all_field(
  File "/Users/mstadelman/Development/iml/dataclasses-json/dataclasses_json/undefined.py", line 249, in _get_catch_all_field
    raise UndefinedParameterError(
dataclasses_json.undefined.UndefinedParameterError: No field of type dataclasses_json.CatchAll defined
```

## Potential Fix:
Maybe this is too naive? 
```
    @staticmethod
    def _get_catch_all_field(cls) -> Field:
        catch_all_fields = list(
            filter(lambda f: f.type == Optional[CatchAllVar] or f.type == 'CatchAll', fields(cls)))
        number_of_catch_all_fields = len(catch_all_fields)
        if number_of_catch_all_fields == 0:
            raise UndefinedParameterError(
                "No field of type dataclasses_json.CatchAll defined")
        elif number_of_catch_all_fields > 1:
            raise UndefinedParameterError(
                f"Multiple catch-all fields supplied: "
                f"{number_of_catch_all_fields}.")
        else:
            return catch_all_fields[0]
```

## Versions Checked
Python: 3.9, 3.10
dataclasses-json: 0.5.6, 0.5.7, master

**Comment by george-zubrienko** [comment]
I just noticed in our README there is an explicit note re usage of that import. Closing a wontfix, for now, will revisit in v1.
