### ISSUE TITLE
[BUG] Importing types in `TYPE_CHECKING` causes `NameError`

### ISSUE THREAD

**Issue by bvle** [lidatong/dataclasses-json#533]
### Description

Whenever I use `.from_dict()` (or `.from_json()`) it errors out with a `NameError`, saying that the types haven't been defined, even though it is defined within the `TYPE_CHECKING` block.

```
Traceback (most recent call last):
  File "/home/bvl/dev/dataclasses_json_bug/main.py", line 16, in <module>
    x = Something.from_dict({"thing": 123})
  File "/home/bvl/dev/dataclasses_json_bug/.venv/lib/python3.14/site-packages/dataclasses_json/api.py", line 70, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "/home/bvl/dev/dataclasses_json_bug/.venv/lib/python3.14/site-packages/dataclasses_json/core.py", line 166, in _decode_dataclass
    types = get_type_hints(cls)
  File "/home/bvl/.pyenv/versions/3.14-dev/lib/python3.14/typing.py", line 2432, in get_type_hints
    value = _eval_type(value, base_globals, base_locals, base.__type_params__)
  File "/home/bvl/.pyenv/versions/3.14-dev/lib/python3.14/typing.py", line 473, in _eval_type
    return t._evaluate(globalns, localns, type_params, recursive_guard=recursive_guard)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bvl/.pyenv/versions/3.14-dev/lib/python3.14/typing.py", line 1071, in _evaluate
    eval(self.__forward_code__, globalns, locals_to_pass),
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'Any' is not defined. Did you mean: 'any'?
```

### Code snippet that reproduces the issue

```py
from dataclasses import dataclass
from typing import TYPE_CHECKING

from dataclasses_json import dataclass_json

if TYPE_CHECKING:
    from typing import Any


@dataclass_json
@dataclass
class Something:
    thing: "Any"


x = Something.from_dict({"thing": 123})
print(x)
```

### Describe the results you expected

Everything imported in the `TYPE_CHECKING` block should be imported when needed, as with `.from_dict()`.

From the code snippet above, the expected output is:
```text
Something(thing=123)
```

### Python version you are using

Python 3.14.0a0

### Environment description

dataclasses-json==0.6.6
marshmallow==3.21.2
mypy-extensions==1.0.0
packaging==24.0
typing-inspect==0.9.0
typing_extensions==4.12.1

**Comment by george-zubrienko** [comment]
@bvle alpha version is not something we'll look at right now. Does this reproduce on 3.9-3.12?

**Comment by ghost** [comment]
Newer versions of Python tend to give better errors messages, so that's why I used Python 3.14. I was also able to reproduce the issue in:
- Python 3.6.15
- Python 3.7.17
- Python 3.8.19
- Python 3.9.19
- Python 3.10.14
- Python 3.11.9
- Python 3.12.3
- Python 3.13.0b1
