### ISSUE TITLE
schema().dumps not working properly with field initializers

### ISSUE THREAD

**Issue by ropottnik** [lidatong/dataclasses-json#60]
Consider the following dataclass:
```python
from typing import List

from dataclasses import dataclass, field
from dataclasses_json import dataclass_json

@dataclass_json
@dataclass
class Bar:
    foos: List[str] = field(default_factory=list)
```

using `Bar.schema().dumps(Bar())` gives me the following error:

```
Traceback (most recent call last):
  File "dataclass_test.py", line 20, in <module>
    Bar.schema().dumps(Bar())
  File "~/.venv/venv/lib/python3.6/site-packages/dataclasses_json/api.py", line 100, in schema
    infer_missing)
  File "~/.venv/venv/lib/python3.6/site-packages/dataclasses_json/mm.py", line 90, in _make_default_fields
    cls)
  File "~/.venv/venv/lib/python3.6/site-packages/dataclasses_json/mm.py", line 105, in _make_default_field
    type_arg = type_.___args__[0]
AttributeError: type object 'List' has no attribute '___args__'

Process finished with exit code 1
```

However, it works when the type of `foos` is a `List` of another `dataclass_json`, like this:
```python
@dataclass_json
@dataclass
class Foo:
    one: str


@dataclass_json
@dataclass
class Bar:
    foos: List[Foo] = field(default_factory=list)


if __name__ == "__main__":
    print(Bar.schema().dumps(Bar()))
```

So something seems to be off with types and field initializers

I am using `dataclasses-json==0.2.1`

**Comment by dpeachey** [comment]
I've also just hit upon the exact same issue.
