### ISSUE TITLE
Fails to build schema if the class have enum field

### ISSUE THREAD

**Issue by denisvlah** [lidatong/dataclasses-json#83]
Example:

```
from dataclasses import dataclass
from enum import Enum
from typing import *

from dataclasses_json import dataclass_json


class NodeType(Enum):
    ACTION1 = 'ACTION1'
    ACTION2 = 'ACTION2'


@dataclass_json
@dataclass(unsafe_hash=True)
class Node:
    type: NodeType

if __name__ == '__main__':
   print(Node.schema())
```

**Comment by Peilonrayz** [comment]
What's the error?

**Comment by denisvlah** [comment]
> What's the error?

/home/denisvlah/anaconda3/lib/python3.7/site-packages/dataclasses_json/mm.py:70: UserWarning: Unknown type <enum 'NodeType'> at Node.type: <enum 'NodeType'> It's advised to pass the correct marshmallow type to `mm_field`.
  warnings.warn(f"Unknown type {type_} at {cls.__name__}.{field.name}: {field.type} "
Traceback (most recent call last):
  File "/home/denisvlah/Desktop/Forcive_Ingestion/lzilla/forcive_ml_py/json_test.py", line 20, in <module>
    print(Node.schema().dump(o))
  File "/home/denisvlah/anaconda3/lib/python3.7/site-packages/dataclasses_json/api.py", line 76, in schema
    Schema = build_schema(cls, DataClassJsonMixin, infer_missing, partial)
  File "/home/denisvlah/anaconda3/lib/python3.7/site-packages/dataclasses_json/mm.py", line 113, in build_schema
    schema_ = schema(cls, mixin, infer_missing)
  File "/home/denisvlah/anaconda3/lib/python3.7/site-packages/dataclasses_json/mm.py", line 98, in schema
    t = build_type(type_, options, mixin, field, cls)
  File "/home/denisvlah/anaconda3/lib/python3.7/site-packages/dataclasses_json/mm.py", line 73, in build_type
    return inner(type_, options)
  File "/home/denisvlah/anaconda3/lib/python3.7/site-packages/dataclasses_json/mm.py", line 72, in inner
    return field.Field(**options)
AttributeError: 'Field' object has no attribute 'Field'

**Comment by lidatong** [comment]
Closing due to fix thanks to @FaraSeer
